### ISSUE TITLE
Is the Semantic Supported feature not supported in this version?

### ISSUE THREAD

**Issue by Taolaw** [OMH4ck/PolyGlot#50]
It seems difficult to reproduce the `PHP` and `Lua` cases based on the given README. From my understanding, Ployglot is an excellent fuzzer for language semantics. However, it appears that Semantic Supported is not supported according to the provided README. Is this due to porting issues? The repository hasn't been updated for seven months. Will the author continue to support updates for this repository?

**Comment by Changochen** [comment]
> It seems difficult to reproduce the PHP and Lua cases based on the given README

What do you mean by `reproduce`. Can you provide more info?

> Semantic Supported is not supported according to the provided README. Is this due to porting issues? 

Yes, I am trying to reconstruct the whole project so that it is easily extendable, which requires lots of efforts. I  will continue to update the projects, but not very frequent considering my schedule. For example, you can see from https://github.com/OMH4ck/PolyGlot/blob/main/tests/validation_test.cc that some semantic validation has been migrated, but not enabled yet.
